version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:5.4
    ports:
      - "8000:80"
    restart: "no"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - ./commonsbooking:/var/www/html/wp-content/plugins/commonsbooking
      - ./cb1:/var/www/html/wp-content/plugins/commons-booking

#  db_cb1:
#    image: mysql:5.7
#    volumes:
#      - db_data_cb1:/var/lib/mysql
#    restart: "no"
#    environment:
#      MYSQL_ROOT_PASSWORD: somewordpress
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress
#
#
#  wordpress_cb1:
#    depends_on:
#      - db_cb1
#    image: wordpress:5.4
#    ports:
#      - "8001:80"
#    restart: "no"
#    environment:
#      WORDPRESS_DB_HOST: db_cb1:3306
#      WORDPRESS_DB_USER: wordpress
#      WORDPRESS_DB_PASSWORD: wordpress
#      WORDPRESS_DB_NAME: wordpress
#      WORDPRESS_DEBUG: 1
#    volumes:
#      - ./cb1:/var/www/html/wp-content/plugins/commons-booking
volumes:
  db_data:
  db_data_cb1:
